run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - revive

issues:
  exclude-rules:
    - path: '.*'
      linters:
        - staticcheck
      text: "SA1019"
